name: command_line
on:
  push:
    branches: ['*']

workflow_dispatch:
  inputs: 
    message:
      description: "Message to cowsay"
      default: "moo"

jobs:
  tests:
    strategy:
      matrix:
        python: [3.11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      
      - name: Install cowsay package
        run: |
          python -m pip install --upgrade pip
          python -m pip install . 
      
      - name: Run tests
        run: cowsay "${{ github.event.inputs.message || 'moo' }}"
          # everything that we put in here is a terminal command
          # the behavior on github actions will be basically the same
          # as the behavior in the terminal on your own computer

          # the line below fails right now because cowsay has not been installed
          # run `pip3 install .` to install cowsay to fix this problem
          cowsay 'moo'
